name: CI
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        if: success() || (failure() && steps.clang-format.conclusion == 'failure')
        uses: ./.github/actions/build
