name: CI
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          flakes: nixpkgs#clang-tools_18, nixpkgs#lefthook

      - name: Run clang-format
        id: clang-format
        run: lefthook run clang-format-check

      - name: Build Package
        if: success() || (failure() && steps.clang-format.conclusion == 'failure')
        uses: ./.github/actions/build
        with:
          cache-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
